/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



//todo; add remove csv button 
//error handling 
//design imporvements 
package com.mycompany.pulido_lab2;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvException;
import java.awt.Color;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.apache.commons.math3.linear.LUDecomposition;
import org.apache.commons.math3.linear.MatrixUtils;
import org.apache.commons.math3.linear.RealMatrix;
import org.apache.commons.math3.linear.RealVector;
import java.io.File;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
/**
 *
 * @author Francis
 */




public class Forecost_frame extends javax.swing.JFrame {
    
    //class level Variables
   
    private  List<double[]>mainData;
    private List<Double>lastColumnData;
    private String[] headerArray;
    private double beta1;
    private double beta2;
    private double beta3;
    private double beta4;
    private double beta5;
    /**
     * Creates new form Forecost_frame
     */
    
    //read from file picker and separate the last column from the rest
private void readCSVFile(String filePath) {
    try (CSVReader reader = new CSVReader(new FileReader(filePath))) {
        
        List<String[]> allRows = reader.readAll(); // Reads all rows into a List
        
        boolean isHeader = true;
        for (String[] row : allRows) {
            if (isHeader) { 
                headerArray = row; // Store the header row
                isHeader = false;
                continue;
            }
            try {
                int columnCount = row.length; // Get total columns dynamically
                if (columnCount < 2) continue; // Skip if too few columns
                
                // Separate last column
                double lastValue = Double.parseDouble(row[columnCount - 1].trim());
                lastColumnData.add(lastValue);

                // Store other columns (excluding last one)
                double[] dataRow = new double[columnCount - 1]; 
                for (int i = 0; i < columnCount - 1; i++) { 
                    dataRow[i] = Double.parseDouble(row[i].trim());
                }
                mainData.add(dataRow);
            } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
                System.out.println("Skipping invalid row: " + String.join(", ", row));
                JOptionPane.showMessageDialog(Forecost_frame.this,
                    "An error has occurred. Please try again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (IOException e) {
    }catch (CsvException e) {
         JOptionPane.showMessageDialog(Forecost_frame.this,
             "Error parsing the CSV file: " + e.getMessage(),
             "CSV Parsing Error",
             JOptionPane.ERROR_MESSAGE);}



    
    // Now call processData with the class-level variables

    
    // Process the data as needed (e.g., perform predictions)
}
    public Forecost_frame() {
        initComponents();
        mainData = new ArrayList<>();
        lastColumnData = new ArrayList<>();
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        colmn_6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        colmn_1 = new javax.swing.JTextField();
        colmn_2 = new javax.swing.JTextField();
        colmn_3 = new javax.swing.JTextField();
        colmn_4 = new javax.swing.JTextField();
        colmn_5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        predict = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Beta_1 = new javax.swing.JTextField(15);
        Beta_2 = new javax.swing.JTextField();
        Beta_3 = new javax.swing.JTextField();
        Beta_4 = new javax.swing.JTextField();
        Beta_5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        upload_CSV = new javax.swing.JButton();
        CSV_Field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ForeCost");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        jLabel1.setText("ForeCost");
        jLabel1.setToolTipText("Your #1 Electricity Prediction App");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-money-96.png"))); // NOI18N

        jLabel5.setText("Forecast your Costs");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel8.setText("Predicted Monthly Bill");

        colmn_6.setForeground(new java.awt.Color(204, 204, 204));
        colmn_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colmn_6.setText("Upload CSV");
        colmn_6.setPreferredSize(new java.awt.Dimension(213, 34));
        colmn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colmn_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colmn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colmn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        colmn_1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        colmn_1.setForeground(new java.awt.Color(204, 204, 204));
        colmn_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colmn_1.setText("Upload CSV");
        colmn_1.setToolTipText("");
        colmn_1.setFocusCycleRoot(true);
        colmn_1.setFocusTraversalPolicyProvider(true);
        colmn_1.setNextFocusableComponent(colmn_2);
        colmn_1.setPreferredSize(new java.awt.Dimension(213, 34));
        colmn_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                colmn_1FocusLost(evt);
            }
        });
        colmn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmn_1MouseClicked(evt);
            }
        });

        colmn_2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        colmn_2.setForeground(new java.awt.Color(204, 204, 204));
        colmn_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colmn_2.setText("Upload CSV");
        colmn_2.setPreferredSize(new java.awt.Dimension(213, 34));
        colmn_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                colmn_2FocusLost(evt);
            }
        });
        colmn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmn_2MouseClicked(evt);
            }
        });

        colmn_3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        colmn_3.setForeground(new java.awt.Color(204, 204, 204));
        colmn_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colmn_3.setText("Upload CSV");
        colmn_3.setPreferredSize(new java.awt.Dimension(213, 34));
        colmn_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                colmn_3FocusLost(evt);
            }
        });
        colmn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmn_3MouseClicked(evt);
            }
        });

        colmn_4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        colmn_4.setForeground(new java.awt.Color(204, 204, 204));
        colmn_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colmn_4.setText("Upload CSV");
        colmn_4.setPreferredSize(new java.awt.Dimension(213, 34));
        colmn_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                colmn_4FocusLost(evt);
            }
        });
        colmn_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmn_4MouseClicked(evt);
            }
        });

        colmn_5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        colmn_5.setForeground(new java.awt.Color(204, 204, 204));
        colmn_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colmn_5.setText("Upload CSV");
        colmn_5.setPreferredSize(new java.awt.Dimension(213, 34));
        colmn_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                colmn_5FocusLost(evt);
            }
        });
        colmn_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colmn_5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel6.setText("Your Data ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/352432_info_icon.png"))); // NOI18N
        jLabel7.setToolTipText("Enter your data to predict bill");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        predict.setText("Predict");
        predict.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        predict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(predict, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colmn_5, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(colmn_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colmn_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colmn_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colmn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(100, 100, 100)))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colmn_1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colmn_2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(colmn_3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(colmn_4, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colmn_5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(predict, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Beta_1.setEditable(false);
        Beta_1.setForeground(new java.awt.Color(204, 204, 204));
        Beta_1.setText("Upload CSV");
        Beta_1.setPreferredSize(new java.awt.Dimension(148, 18));
        Beta_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Beta_1ActionPerformed(evt);
            }
        });

        Beta_2.setEditable(false);
        Beta_2.setForeground(new java.awt.Color(204, 204, 204));
        Beta_2.setText("Upload CSV");
        Beta_2.setPreferredSize(new java.awt.Dimension(148, 18));
        Beta_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Beta_2ActionPerformed(evt);
            }
        });

        Beta_3.setEditable(false);
        Beta_3.setForeground(new java.awt.Color(204, 204, 204));
        Beta_3.setText("Upload CSV");
        Beta_3.setPreferredSize(new java.awt.Dimension(148, 18));
        Beta_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Beta_3ActionPerformed(evt);
            }
        });

        Beta_4.setEditable(false);
        Beta_4.setForeground(new java.awt.Color(204, 204, 204));
        Beta_4.setText("Upload CSV");
        Beta_4.setPreferredSize(new java.awt.Dimension(148, 18));
        Beta_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Beta_4ActionPerformed(evt);
            }
        });

        Beta_5.setEditable(false);
        Beta_5.setForeground(new java.awt.Color(204, 204, 204));
        Beta_5.setText("Upload CSV");
        Beta_5.setPreferredSize(new java.awt.Dimension(148, 18));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/352432_info_icon.png"))); // NOI18N
        jLabel3.setToolTipText("The following is the bias derived from our data");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel2.setText("BIAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Beta_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Beta_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Beta_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Beta_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Beta_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Beta_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Beta_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Beta_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Beta_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Beta_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        upload_CSV.setText("Upload CSV");
        upload_CSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_CSVActionPerformed(evt);
            }
        });

        CSV_Field.setEditable(false);
        CSV_Field.setText("None");
        CSV_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSV_FieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Current CVS:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(upload_CSV)
                                .addGap(0, 151, Short.MAX_VALUE))
                            .addComponent(CSV_Field))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CSV_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upload_CSV)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Beta_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Beta_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Beta_4ActionPerformed

    private void Beta_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Beta_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Beta_3ActionPerformed

    private void Beta_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Beta_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Beta_1ActionPerformed

    private void Beta_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Beta_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Beta_2ActionPerformed
//olve when button is being pressed
    private void predictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictActionPerformed
        double[][] X_data = mainData.toArray(new double[0][0]);
        double[] y_data = lastColumnData.stream().mapToDouble(Double::doubleValue).toArray(); 
        // Create RealMatrix objects for X and y
        RealMatrix X = MatrixUtils.createRealMatrix(X_data);
        RealVector y = MatrixUtils.createRealVector(y_data);
        // Calculate X^T (transpose of X)
        RealMatrix Xt = X.transpose();
        // Calculate (X^T * X) and its inverse
        RealMatrix Xt_MultipliedByX = Xt.multiply(X);
        RealMatrix Inverse_Xt_MultipliedByX = new LUDecomposition(Xt_MultipliedByX).getSolver().getInverse();
        // Convert y to a RealMatrix column vector (n x 1 matrix)
        RealMatrix yMatrix = MatrixUtils.createColumnRealMatrix(y.toArray());
        // Calculate beta (coefficients) using the formula: beta = (X^T * X)^(-1) * X^T * y
        RealMatrix beta = Inverse_Xt_MultipliedByX.multiply(Xt).multiply(yMatrix);
        // Extract the coefficients as a RealVector (1D array)
        RealVector betaVector = beta.getColumnVector(0);
        // Display the coefficients (beta values)     
        
        // Allow user to input features for prediction
        double usage = Double.parseDouble(colmn_1.getText());
              
        double numMembers = Double.parseDouble(colmn_2.getText());

        double appliances = Double.parseDouble(colmn_3.getText());

        double income = Double.parseDouble(colmn_4.getText());
        
        double homesize = Double.parseDouble(colmn_5.getText());
        

        // Create a new feature vector (including the intercept term)
        double[] newHouse = {usage, 
                             numMembers, 
                             appliances,
                             income,
                             homesize}; // Intercept term + size, bedrooms, location

        // Convert the new house row to a RealVector
        RealVector row = MatrixUtils.createRealVector(newHouse);

        // Calculate the predicted price using the dot product of the feature vector and the beta coefficients
        double predictedPrice = row.dotProduct(betaVector);

        // Output the predicted price
        colmn_6.setText(Double.toString(predictedPrice));
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forecost_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //
        
        //
    }//GEN-LAST:event_predictActionPerformed

    private void colmn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colmn_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colmn_6ActionPerformed

    private void CSV_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSV_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSV_FieldActionPerformed

    private void colmn_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colmn_1FocusLost
        // TODO add your handling code here:
        if(colmn_1.getText().trim().isEmpty())
       {
           colmn_1.setText(headerArray[0]);
       }
        
    }//GEN-LAST:event_colmn_1FocusLost

    private void colmn_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmn_1MouseClicked
        // TODO add your handling code here:
           if(colmn_1.getText().trim().equals(headerArray[0]))
       {
           colmn_1.setText("");
       }

    }//GEN-LAST:event_colmn_1MouseClicked

    private void colmn_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmn_2MouseClicked
           if(colmn_2.getText().trim().equals(headerArray[1]))
       {
           colmn_2.setText("");
       }

    }//GEN-LAST:event_colmn_2MouseClicked

    private void colmn_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colmn_2FocusLost
        // TODO add your handling code here:
           if(colmn_2.getText().trim().isEmpty())
       {
           colmn_2.setText(headerArray[1]);
       }

    }//GEN-LAST:event_colmn_2FocusLost

    private void colmn_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colmn_3FocusLost
        // TODO add your handling code here:
         if(colmn_3.getText().trim().isEmpty())
       {
          colmn_3.setText(headerArray[2]);
       }

    }//GEN-LAST:event_colmn_3FocusLost

    private void colmn_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmn_3MouseClicked
        // TODO add your handling code here:

                 if(colmn_3.getText().trim().equals(headerArray[2]))
       {
           colmn_3.setText("");
       }

    }//GEN-LAST:event_colmn_3MouseClicked

    private void colmn_4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colmn_4FocusLost
        // TODO add your handling code here:
        if(colmn_4.getText().trim().isEmpty())
       {
           colmn_4.setText(headerArray[3]);
       }

    }//GEN-LAST:event_colmn_4FocusLost

    private void colmn_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmn_4MouseClicked
        // TODO add your handling code here:
         if(colmn_4.getText().trim().equals(headerArray[3]))
       {
           colmn_4.setText("");
       }

    }//GEN-LAST:event_colmn_4MouseClicked

    private void colmn_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colmn_5MouseClicked
        // TODO add your handling code here:

        if(colmn_5.getText().trim().equals(headerArray[4]))
       {
           colmn_5.setText("");
       }
      
    }//GEN-LAST:event_colmn_5MouseClicked

    private void colmn_5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_colmn_5FocusLost
        // TODO add your handling code here:
        if(colmn_5.getText().trim().isEmpty())
       {
           colmn_5.setText(headerArray[4]);
       }
    }//GEN-LAST:event_colmn_5FocusLost

    private void upload_CSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_CSVActionPerformed
        // TODO add your handling code here:


                             
     mainData.clear();
     lastColumnData.clear();
    
     JFXPanel jfxPanel = new JFXPanel(); // This initializes the JavaFX runtime

    // Use Platform.runLater to ensure JavaFX runs on the JavaFX Application Thread
     Platform.runLater(new Runnable() {
         @Override
         public void run() {
            try{
                      
             FileChooser fileChooser = new FileChooser();
             fileChooser.setTitle("Select a CSV File");
             
             // Set file extension filters (optional)
             fileChooser.getExtensionFilters().addAll(
                     new FileChooser.ExtensionFilter("CSV Files", "*.csv"),
                     new FileChooser.ExtensionFilter("All Files", "*.*")
             );
             
             // Show the open dialog and get the selected file
             Stage stage = new Stage();
             File fileToOpen = fileChooser.showOpenDialog(stage); // Use 'this' if it's a JFrame
             
             // Check if a file was selected

             if (fileToOpen != null) {
                 String filePath = fileToOpen.getAbsolutePath();
                 readCSVFile(filePath); // Call your method to read the CSV file
                 CSV_Field.setText(fileToOpen.getName()); // Set the name of the selected file
                 
                 // Process the data as needed
                 double[][] X_data = mainData.toArray(new double[0][0]);
                 double[] y_data = lastColumnData.stream().mapToDouble(Double::doubleValue).toArray();
                 // Create RealMatrix objects for X and y
                 RealMatrix X = MatrixUtils.createRealMatrix(X_data);
                 RealVector y = MatrixUtils.createRealVector(y_data);
                 // Calculate X^T (transpose of X)
                 RealMatrix Xt = X.transpose();
                 // Calculate (X^T * X) and its inverse
                 RealMatrix Xt_MultipliedByX = Xt.multiply(X);
                 RealMatrix Inverse_Xt_MultipliedByX = new LUDecomposition(Xt_MultipliedByX).getSolver().getInverse();
                 // Convert y to a RealMatrix column vector (n x 1 matrix)
                 RealMatrix yMatrix = MatrixUtils.createColumnRealMatrix(y.toArray());
                 // Calculate beta (coefficients) using the formula: beta = (X^T * X)^(-1) * X^T * y
                 RealMatrix beta = Inverse_Xt_MultipliedByX.multiply(Xt).multiply(yMatrix);
                 // Extract the coefficients as a RealVector (1D array)
                 RealVector betaVector = beta.getColumnVector(0);
                 // Display the coefficients (beta values)
                 
                 Beta_1.setText(Double.toString(betaVector.getEntry(0)));
                 Beta_2.setText(Double.toString(betaVector.getEntry(1)));
                 Beta_3.setText(Double.toString(betaVector.getEntry(2)));
                 Beta_4.setText(Double.toString(betaVector.getEntry(3)));
                 Beta_5.setText(Double.toString(betaVector.getEntry(4)));
                 
                 // Set font from grey to black
                 Beta_1.setForeground(Color.BLACK);
                 Beta_2.setForeground(Color.BLACK);
                 Beta_3.setForeground(Color.BLACK);
                 Beta_4.setForeground(Color.BLACK);
                 Beta_5.setForeground(Color.BLACK);
                 
                 colmn_1.setText(headerArray[0]);
                 colmn_2.setText(headerArray[1]);
                 colmn_3.setText(headerArray[2]);
                 colmn_4.setText(headerArray[3]);
                 colmn_5.setText(headerArray[4]);
                 colmn_6.setText(headerArray[5]);
                 colmn_1.setForeground(Color.BLACK);
                 colmn_2.setForeground(Color.BLACK);
                 colmn_3.setForeground(Color.BLACK);
                 colmn_4.setForeground(Color.BLACK);
                 colmn_5.setForeground(Color.BLACK);
                 colmn_6.setForeground(Color.BLACK);
                 
             } 
             else 
             {
                 // Handle the case where no file was selected (optional)
                 System.out.println("File selection was canceled.");
             }
            }
            catch(NumberFormatException|ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(Forecost_frame.this,
             "Thats The WRONG FILE dumb piece of shit",
             "DUMB SHIT",
             JOptionPane.ERROR_MESSAGE);
                
            }
           }
          }
         );
     
             
             
             

    }//GEN-LAST:event_upload_CSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Forecost_frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Beta_1;
    private javax.swing.JTextField Beta_2;
    private javax.swing.JTextField Beta_3;
    private javax.swing.JTextField Beta_4;
    private javax.swing.JTextField Beta_5;
    private javax.swing.JTextField CSV_Field;
    private static javax.swing.JTextField colmn_1;
    private static javax.swing.JTextField colmn_2;
    private static javax.swing.JTextField colmn_3;
    private static javax.swing.JTextField colmn_4;
    private static javax.swing.JTextField colmn_5;
    private static javax.swing.JTextField colmn_6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton predict;
    private javax.swing.JButton upload_CSV;
    // End of variables declaration//GEN-END:variables
}
